### ISSUE TITLE
Carry www-servers/nginx through proxy-maintainers?

### ISSUE THREAD

**Issue by jbergstroem** [gentoo/proxy-maintainers#10]
Hey,

@dev-zero and I manage the [nginx-overlay](https://github.com/gentoo/nginx-overlay), a git repo where we do most nginx development, but also carry older versions. Since it's a pretty well used software, we thought it could benefit from having its own "entity". Also, it makes it easier for non-developers (read: me) to contribute.

Since @dev-zero is pretty busy every now and then I just wanted to explore the possibility of carrying versions that should end up in gentoo-x86 through this repo. If so, I'll still carry on with the development effort in the overlay, then do sync/verbump pull requests to this. Hopefully I can merge the commits, but it won't be one of my goals.

Thoughts?

**Comment by mrueg** [comment]
Feel free to add a pull request.
